### ISSUE TITLE
Prevent deletion of non-empty widgets

### ISSUE THREAD

**Issue by senekor** [senekor/buenzlimarks#103]
As stated in the requirement #10, non-empty widgets should not be able to be deleted.

Most importantly, this should be enforced on the backend.

However, to ensure a good user experience, let's also prevent the user from deleting non-empty widgets in the first place on the frontend. For example, the button that deletes a widget could be disabled and greyed out a little for visual distinction.

And while we're at it, let's also do the same for pages. Same problem there.

**Comment by Robrisi** [comment]
We have discussed to add a confirmation dialog in the UI instead. (for widgets and pages, not bookmarks)
